// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqTFUZfJYXU0btonzHz33w2LHAwGWs2mw',
    appId: '1:863490886076:web:9f62bcd02260be4b1fc3b9',
    messagingSenderId: '863490886076',
    projectId: 'couplesharmony-test-app',
    authDomain: 'couplesharmony-test-app.firebaseapp.com',
    storageBucket: 'couplesharmony-test-app.firebasestorage.app',
    measurementId: 'G-ZC1TZFP5Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBO_-UQlbGvmEm04D8u76WrvHDWJURfzQ',
    appId: '1:863490886076:android:32081e54eed51ff51fc3b9',
    messagingSenderId: '863490886076',
    projectId: 'couplesharmony-test-app',
    storageBucket: 'couplesharmony-test-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABGaOV873dVk1NBk263omB5JqM5Z18Gh8',
    appId: '1:863490886076:ios:27aba7444bae47e91fc3b9',
    messagingSenderId: '863490886076',
    projectId: 'couplesharmony-test-app',
    storageBucket: 'couplesharmony-test-app.firebasestorage.app',
    iosBundleId: 'com.example.couplesHarmony',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqTFUZfJYXU0btonzHz33w2LHAwGWs2mw',
    appId: '1:863490886076:web:5b3a0fa3b5b62d661fc3b9',
    messagingSenderId: '863490886076',
    projectId: 'couplesharmony-test-app',
    authDomain: 'couplesharmony-test-app.firebaseapp.com',
    storageBucket: 'couplesharmony-test-app.firebasestorage.app',
    measurementId: 'G-GW2VP8MFFL',
  );
}
